### ISSUE TITLE
Enhancement Request for Player Props

### ISSUE THREAD

**Issue by aaronmorrisNC** [sportsdataverse/oddsapiR#3]
Hi Saiem.  Now that player props are available will there be any functionality added to the oddsapiR package?

https://the-odds-api.com/sports-odds-data/betting-markets.html#player-props-api-markets

**Comment by saiemgilani** [comment]
Added via `toa_event_odds()`

**Comment by saiemgilani** [comment]
As of oddsapiR v0.0.3 (now available on CRAN), this is supported via the `toa_event_odds()` function.

Additionally, the function for historical odds has also been added `toa_sports_odds_history()`

Closing
